project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550"
  page-footer:
    left: "© 2024 Emily Zhou. All Rights Reserved."
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
  back-to-top-navigation: true
  page-navigation: true
  repo-url: https://github.com/emilyzhou112/MUSA550-PA-CRD-Prediction
  repo-actions: [source]

  sidebar:
    logo: "assets/copd.jpg"
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://emilyzhou112.github.io/
        text: "Visit my Website" 
      - icon: github
        href: https://github.com/emilyzhou112/MUSA550-PA-CRD-Prediction
        text: "View on GitHub"
      - icon: envelope
        href: emzhou@design.upenn.edu
        text: "Contact Me"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: introduction.qmd
        text: Introduction
      - section: Methodology
        contents:
          - analysis/RasterData.ipynb
          - analysis/VectorData.ipynb
          - analysis/PrepareML.ipynb
          - analysis/PrevalenceEst.ipynb
      - section: Results
        contents:
          - analysis/VarCompare.ipynb
          - analysis/ModelCompare.ipynb
      - href: discussions.qmd
        text: Discussions
      - href: citations.qmd
        text: References

format:
  html:
    highlight-style: solarized
    theme: [cosmo, pages.scss]
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
