# References

1. WHO. The Global Impact of Respiratory Disease | WHO; 2020. [https://www.who.int/gard/publications/The_Global_Impact_of_Respiratory_Disease.pdf.](https://www.who.int/gard/publications/The_Global_Impact_of_Respiratory_Disease.pdf)

2. Wheaton AG, Cunningham TJ, Ford ES, Croft JB. Employment and activity limitations among adults with chronic obstructive pulmonary disease—United States, 2013. MMWR Morbidity and mortality weekly report. 2015;64(11):289.

3. National Center for Health Statistics U. Health, United States, 2015: with special feature on racial and ethnic health disparities. 2016.

4. CDC. Certain Medical Conditions and Risk for Severe COVID-19 Illness | CDC; 2020. [https://www.cdc.gov/coronavirus/2019-ncov/need-extra-precautions/people-with-medical-conditions.html](https://www.cdc.gov/coronavirus/2019-ncov/need-extra-precautions/people-with-medical-conditions.html)

5. Kurmi OP, Semple S, Simkhada P, Smith WCS, Ayres JG. COPD and chronic bronchitis risk of indoor air pollution from solid fuel: a systematic review and meta-analysis. Thorax. 2010;65(3):221–228. doi: 10.1136/thx.2009.124644 

6. Peacock JL, Anderson HR, Bremner SA, Marston L, Seemungal TA, Strachan DP, et al. Outdoor air pollution and respiratory health in patients with COPD. Thorax. 2011;66(7):591–596. doi: 10.1136/thx.2010.155358

7. Berry CE, Wise RA. Mortality in COPD: causes, risk factors, and prevention. COPD: Journal of Chronic Obstructive Pulmonary Disease. 2010;7(5):375–382. doi: 10.3109/15412555.2010.510160

8. 500 Cities. 500 Cities Project: Local Data for Better Health; 2024 [https://data.cdc.gov/500-Cities-Places/PLACES-Local-Data-for-Better-Health-Census-Tract-D/cwsq-ngmh/about_data](https://data.cdc.gov/500-Cities-Places/PLACES-Local-Data-for-Better-Health-Census-Tract-D/cwsq-ngmh/about_data)

9. Census gov. Census Tracts; 2022. [https://data.census.gov/advanced](https://data.census.gov/advanced)

10. Zhang X, Holt JB, Lu H, Wheaton AG, Ford ES, Greenlund KJ, et al. Multilevel regression and poststratification for small-area estimation of population health outcomes: a case study of chronic obstructive pulmonary disease prevalence using the behavioral risk factor surveillance system. American journal of epidemiology. 2014;179(8):1025–1033. doi: 10.1093/aje/kwu018

11. Leas EC, Schleicher NC, Prochaska JJ, Henriksen L. Place-Based Inequity in Smoking Prevalence in the Largest Cities in the United States. JAMA internal medicine. 2019;179(3):442–444. doi: 10.1001/jamainternmed.2018.5990

12. MLRC. NLCD 2021 Land Cover (CONUS) | Multi-Resolution Land Characteristics (MRLC) consortium; 2021. [https://www.mrlc.gov/data/nlcd-2021-land-cover-conus](https://www.mrlc.gov/data/nlcd-2021-land-cover-conus)

13. Rehman NA, Relia K, Chunara R. Creating full individual-level location timelines from sparse social media data. In: Proceedings of the 26th ACM SIGSPATIAL International Conference on Advances in Geographic Information Systems. ACM; 2018. p. 379–388.

14. Leas EC, Schleicher NC, Prochaska JJ, Henriksen L. Place-Based Inequity in Smoking Prevalence in the Largest Cities in the United States. JAMA Intern Med. 2019;179(3):442–444. doi:10.1001/jamainternmed.2018.5990

15. Feng, Yinhe et al. “Artificial Intelligence and Machine Learning in Chronic Airway Diseases: Focus on Asthma and Chronic Obstructive Pulmonary Disease.” International journal of medical sciences vol. 18,13 2871-2889. 1 Jun. 2021, doi:10.7150/ijms.58191

16. Alvarez-Mendoza, C. I., Teodoro, A., Freitas, A., & Fonseca, J. (2020). Spatial estimation of chronic respiratory diseases based on machine learning procedures—An approach using remote sensing data and environmental variables in quito, Ecuador. Applied Geography, 123, 102273.

17. So, J. Y., Zhao, H., Voelker, H., Reed, R. M., Sin, D., Marchetti, N., & Criner, G. J. (2018). Seasonal and regional variations in chronic obstructive pulmonary disease exacerbation rates in adults without cardiovascular risk factors. Annals of the American Thoracic Society, 15(11), 1296-1303.

18. USGS. Landsat 8 Level 2, Collection 2, Tier 1 | U.S. Geological Survey; 2024. [https://developers.google.com/earth-engine/datasets/catalog/LANDSAT_LC08_C02_T1_L2#description](https://developers.google.com/earth-engine/datasets/catalog/LANDSAT_LC08_C02_T1_L2#description)

19. Open Data PA. Tobacco Products Tax Licenses Current Daily County Revenue | Pennsylvania Office of Open Data; 2024. [https://data.pa.gov/Licenses-Certificates/Tobacco-Products-Tax-Licenses-Current-Daily-County/ut72-sft8/about_data](https://data.pa.gov/Licenses-Certificates/Tobacco-Products-Tax-Licenses-Current-Daily-County/ut72-sft8/about_data)

20. Abdur Rehman, N., & Counts, S. (2021). Neighborhood level chronic respiratory disease prevalence estimation using search query data. PloS one, 16(6), e0252383. 


